services:
  registryservice:
    image: registryservice
    ports:
      - "7000:5118"
    build:
      context: .
      dockerfile: RegistryService/Dockerfile
    networks:
      - network-micromart

  taxcalculatorapi:
    image: taxcalculatorapi
    build:
      context: .
      dockerfile: TaxCalculatorApi/Dockerfile
    depends_on:
      - registryservice
    networks:
      - network-micromart

  invoicenumbergeneratorapi:
    image: invoicenumbergeneratorapi
    build:
      context: .
      dockerfile: InvoiceNumberGeneratorApi/Dockerfile
    depends_on:
      - registryservice
    networks:
      - network-micromart

  discountengineapi:
    image: discountengineapi
    build:
      context: .
      dockerfile: DiscountEngineApi/Dockerfile
    depends_on:
      - registryservice
    networks:
      - network-micromart

networks:
  network-micromart:
    driver: 
      bridge
